[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ACOS-4-5.x-to-6-upgrade"
authors = [{name = "Glen Townsend", email = "gtownsend@a10networks.com"}]
dynamic = ["version", "description"]
